### ISSUE TITLE
importing module 'fleet_rent': 'Unmet module dependencies: ow_account_asset, ow_account_budget, fleet_operations

### ISSUE THREAD

**Issue by rithin** [JayVora-SerpentCS/fleet_management#23]
Hi,
Am getting an error when installing fleet_rent module. 

Error while importing module 'fleet_rent': 'Unmet module dependencies: ow_account_asset, ow_account_budget, fleet_operations\n' Error while importing module 'fleet_operations': 'Unmet module dependencies: web_widget_multi_image\n' Error while importing module 'web_widget_multi_image': "Module loading web_widget_multi_image failed: file /tmp/tmpy_3neaxt/web_widget_multi_image/security/ir.model.access.csv could not be processed:\n No matching record found for external id 'model_multi_images' in field 'Object'\nMissing required value for the field 'Object' (model_id)" Error while importing module 'ow_account_asset': 'External ID not found in the system: ow_account_asset.model_account_asset_category\n<record id="account_asset_category_multi_company_rule" model="ir.rule">\n <field name="name">Account Asset Category multi-company</field>\n <field ref="model_account_asset_category" name="model_id"/>\n <field eval="True" name="global"/>\n <field name="domain_force">[\'\|\',(\'company_id\',\'=\',False),(\'company_id\',\'child_of\',[user.company_id.id])]</field>\n </record>\n/tmp/tmpy_3neaxt/ow_account_asset/security/account_asset_security.xml\n4' Error while importing module 'ow_account_budget': "Module loading ow_account_budget failed: file /tmp/tmpy_3neaxt/ow_account_budget/security/ir.model.access.csv could not be processed:\n No matching record found for external id 'model_crossovered_budget' in field 'Object'\nNo matching record found for external id 'model_account_budget_post' in field 'Object'\nNo matching record found for external id 'model_account_budget_post' in field 'Object'\nNo matching record found for external id 'model_crossovered_budget' in field 'Object'\nNo matching record found for external id 'model_crossovered_budget_lines' in field 'Object'\nNo matching record found for external id 'model_crossovered_budget_lines' in field 'Object'\nMissing required value for the field 'Object' (model_id)\nMissing required value for the field 'Object' (model_id)\nMissing required value for the field 'Object' (model_id)\nMissing required value for the field 'Object' (model_id)\nMissing required value for the field 'Object' (model_id)\nMissing required value for the field 'Object' (model_id)"
-

I tried to install all the dependency modules also, but the same kind of error coming for those modules as well.

**Comment by YogendrasinhChavda** [comment]
Hello @rithin,

Our Fleet Operations and Fleet Rental Management modules are only for the Odoo Community Edition (CE).
Your Demo instance is in 12.0 Enterprise Edition, so our module may be not working with odoo EE.
If you want to use our modules then Install our modules with Community Edition (CE).

Below is some screenshot of your demo instance information.

![Fleet_instance_ee_rithin](https://user-images.githubusercontent.com/11770935/58682770-7cde0d80-838f-11e9-8e7e-99b5f63d0ea8.png)

![Fleet_instance_ee_module_not_found_rithin](https://user-images.githubusercontent.com/11770935/58682793-94b59180-838f-11e9-988b-126b4db4294c.png)


Thank you.

**Comment by rithin** [comment]
Thanks for the clarification. I'll try on the community edition.
