### ISSUE TITLE
v13 - Drivers History menu is missing form fleet operations 

### ISSUE THREAD

**Issue by mita4kata** [JayVora-SerpentCS/fleet_management#40]
Drivers History menu is missing

**Comment by ChavdaRiddhi** [comment]
Hello  @mita4kata ,
Please install the module fleet_rent after that you can see the Fleet Driver menu.

**Comment by mita4kata** [comment]
Hi , 
after module fleet_rent installed Fleet Driver menu is still missing from Smart button and button on the top of the form view, as you can see below 
![image](https://user-images.githubusercontent.com/50295420/75585696-5b739480-5a7b-11ea-88eb-22c0415281bd.png)

**Comment by ChavdaRiddhi** [comment]
hello @mita4kata ,
please see the below attached screenshot. you can find the fleet driver menu as per mentioned in below screenshot.
![fleetdriverissue](https://user-images.githubusercontent.com/50871920/75776129-624f1f80-5d79-11ea-9a34-e336f4b9cd29.png)
Thanks

**Comment by mita4kata** [comment]
Dear @ChavdaRiddhi , 
i would like to note you about the default functionality of v13 is to be able to get a history of driven cars from employees.  Fleet operation module doesn't inherit the Drivers History 
 

![Capture](https://user-images.githubusercontent.com/50295420/75919948-23979300-5e67-11ea-9549-1831692cbb32.PNG)

**Comment by ChavdaRiddhi** [comment]
hello @mita4kata ,
we added driver change history log button as per odoo 13.0 CE.
https://github.com/JayVora-SerpentCS/fleet_management/pull/47
please take the latest update and check.
Thanks
