### ISSUE TITLE
Error while trying assign driver to a car

### ISSUE THREAD

**Issue by falmic** [JayVora-SerpentCS/fleet_management#5]
Hi, on clean Odoo community 11 install, I add fleet_management.
When I create new car and try assign driver I get error:

TypeError: undefined is not an object (evaluating 'nameGet[1]')
http://xxx.xxx.xxx.xxx/web/content/557-288ea84/web.assets_backend.js:1192
Traceback:
http://xxx.xxx.xxx.xxx/web/content/557-288ea84/web.assets_backend.js:1192:382
forEach@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:12:566
http://xxx.xxx.xxx.xxx/web/content/557-288ea84/web.assets_backend.js:1192:248
http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:802:686
fire@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:796:304
fireWith@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:801:202
http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:803:56
http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:3869:363
http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:802:686
fire@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:796:304
fireWith@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:801:202
http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:803:56
fire@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:796:304
fireWith@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:801:202
http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:802:874
fire@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:796:304
fireWith@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:801:202
http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:802:874
fire@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:796:304
fireWith@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:801:202
done@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:1192:106
callback@http://xxx.xxx.xxx.xxx/web/content/548-3e58a25/web.assets_common.js:1212:23

I test this on clean database and database with demo data. but same problem.

**Comment by JayVora-SerpentCS** [comment]
@YogendrasinhChavda

**Comment by YogendrasinhChavda** [comment]
Hello @falmic, @JayVora-SerpentCS,

We tested scenario with odoo CE 11 to set driver in a new vehicle (new car) by creating the new fresh database with demo data and without demo data.
it is working fine, I mean we didn't face any issue.

Thanks
