### ISSUE TITLE
After install module the label of sales/purchase info in contacts/ customers/ vendors is hided

### ISSUE THREAD

**Issue by kimbo23** [JayVora-SerpentCS/fleet_management#59]
After install this module the label of sales/purchase info in contacts/ customers/ vendors is hided

**Comment by YogendrasinhChavda** [comment]
Hello @kimbo23 ,

Which odoo Version you are using ?

Thanks

**Comment by YogendrasinhChavda** [comment]
Hello @kimbo23 

if you are using the version 13 OR 14, As per your request we improved the Sales/Purchase information in contact.
Please take latest updated code and check.

Thanks

**Comment by kimbo23** [comment]
Thank you for your fast reply

**Comment by kimbo23** [comment]
Thank you is solved this issue. I´ll open a new one with problem to open report update next service day
