### ISSUE TITLE
Unable to install Fleet Operations module for Odoo 14 , I will post the error log below

### ISSUE THREAD

**Issue by davidwoodroffe28-dev** [JayVora-SerpentCS/fleet_management#64]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\web\controllers\main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\web\controllers\main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\modules\loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\modules\loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\modules\loading.py", line 187, in load_module_graph
    model_names = registry.load(cr, package)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\modules\registry.py", line 232, in load
    model = cls._build_model(self, cr)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\models.py", line 550, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: Model 'fleet.vehicle.log.fuel' does not exist in registry.

**Comment by YogendrasinhChavda** [comment]
Hello @davidwoodroffe28-dev 

As per error log, you are using odoo 14 and windows OS. Right ?
Which Odoo Edition you are using ? I mean CE ( Community Edition ) or EE ( Enterprise Edition ) ?

Please make sure you are using valid fleet_management branch addons ? i mean if you clone addons ( modules ) from github,  it will default clone / pull module for odoo 13.0.

We will check and update you as soon as possible.

Thanks

**Comment by davidwoodroffe28-dev** [comment]
HI

> Hello @davidwoodroffe28-dev
> 
> As per error log, you are using odoo 14 and windows OS. Right ?
> Which Odoo Edition you are using ? I mean CE ( Community Edition ) or EE ( Enterprise Edition ) ?
> 
> Please make sure you are using valid fleet_management branch addons ? i mean if you clone addons ( modules ) from github, it will default clone / pull module for odoo 13.0.
> 
> We will check and update you as soon as possible.
> 
> Thanks

Thank you for you response , I am using Odoo 14 and Windows Os , I am also using  CE edition

**Comment by YogendrasinhChavda** [comment]
Hello @davidwoodroffe28-dev 

We tested just now fleet application with fresh database. ( odoo 14 CE And Ubuntu 20.04.1 LTS )
and Its working fine. i mean we didn't face any issue. but as per your error log we did small improvements by removing deprecated model's test case.
So, Please take latest Pull/Clone from github branch https://github.com/JayVora-SerpentCS/fleet_management/tree/14.0
and Test Again.

Thanks

**Comment by davidwoodroffe28-dev** [comment]
Hello getting a different issue now .

**Comment by davidwoodroffe28-dev** [comment]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\tools\convert.py", line 677, in _tag_root
    f(rec)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\tools\convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\models.py", line 4209, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\models.py", line 4138, in _load_records_create
    return self.create(values)
  File "<decorator-gen-42>", line 2, in create
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_ui_view.py", line 482, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\models.py", line 3899, in create
    fields[0].determine_inverse(batch_recs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\fields.py", line 1183, in determine_inverse
    getattr(records, self.inverse)()
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\website\models\theme_models.py", line 267, in write
    res = super(IrUiView, other_views).write(vals)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\website\models\ir_ui_view.py", line 68, in write
    return super(View, self).write(vals)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\models.py", line 3688, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\models.py", line 1256, in _validate_fields
    check(self)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_ui_view.py", line 411, in _check_xml
    )).with_traceback(e.__traceback__) from None
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_ui_view.py", line 865, in _postprocess_view
    name_manager.check_view_fields(self)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_ui_view.py", line 1992, in check_view_fields
    view.handle_view_error(msg)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Error while validating view:

Field custom_product_id used in attrs.invisible ({'invisible': [('custom_product_id', '!=', False)]}) must be present in view but is missing.

View name: fleet.vehicle.model.form.extended
Error context:
 view: ir.ui.view(3080,)
 xmlid: fleet_vehicle_model_form_extended
 view.model: fleet.vehicle
 view.parent: ir.ui.view(1016,)
 file: c:\program files\odoo 14.0.20210206\server\odoo\addons\fleet_operations\views\fleet_extended_view.xml


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\web\controllers\main.py", line 1381, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\web\controllers\main.py", line 1369, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\addons\base\models\ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\modules\loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\modules\loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\modules\loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\modules\loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\tools\convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\tools\convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\tools\convert.py", line 719, in parse
    self._tag_root(de)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\tools\convert.py", line 685, in _tag_root
    )) from e
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files\Odoo 14.0.20210206\server\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing file:/c:/program%20files/odoo%2014.0.20210206/server/odoo/addons/fleet_operations/views/fleet_extended_view.xml:160, near
<record model="ir.ui.view" id="fleet_vehicle_model_form_extended">
        <field name="name">fleet.vehicle.model.form.extended</field>
        <field name="model">fleet.vehicle</field>
        <field name="inherit_id" ref="fleet.fleet_vehicle_view_form"/>
        <field name="arch" type="xml">
            <data><xpath expr="//header/field[@name='state_id']" position="replace">
                <button name="set_released_state" class="oe_highlight" type="object" string="Released" states="complete" groups="fleet.fleet_group_manager" help="set the vehicle status to released if the status is compelte.">
                </button>
                <button name="update_history" type="object" string="Update Engine" context="{'history':'engine'}" icon="fa-gears" class="oe_stat_button oe_highlight" groups="fleet.fleet_group_manager" attrs="{'invisible':[('state','in',('write-off'))]}"/>
                <button name="update_history" type="object" string="Update Color" context="{'history':'color'}" icon="fa-gears" class="oe_stat_button oe_highlight" groups="fleet.fleet_group_manager" attrs="{'invisible':[('state','in',('write-off'))]}"/>
                <button name="update_history" type="object" string="Update Tire" context="{'history':'tire'}" icon="fa-gears" class="oe_stat_button oe_highlight" groups="fleet.fleet_group_manager" attrs="{'invisible':[('state','in',('write-off'))]}"/>
                <button name="update_history" type="object" string="Update Battery" context="{'history':'battery'}" icon="fa-gears" class="oe_stat_button oe_highlight" groups="fleet.fleet_group_manager" attrs="{'invisible':[('state','in',('write-off'))]}"/>
                        
                <button name="%(fleet_operations.fleet_vehicle_log_services_form_action)d" type="action" string="Services" icon="fa-gears" class="oe_stat_button oe_highlight" domain="[('state','in',('inspection','released'))]" context="{'default_vehicle_id': active_id}"/>
                <button name="%(fleet_operations.fleet_vehicle_write_off_form_action)d" type="action" string="Write-off" icon="fa-gears" class="oe_stat_button oe_highlight" domain="[('state','in',('inspection','released'))]" context="{'default_vehicle_id': active_id}"/>
                <field name="state" widget="statusbar" statusbar_visible="inspection,in_progress,complete"/>
            </xpath>

            <xpath expr="//div[@name='button_box']" position="replace">
                <div class="oe_button_box" name="button_box">
                    <button name="open_assignation_logs" type="object" class="oe_stat_button" icon="fa-history" help="show all the driver history" groups="fleet.fleet_group_manager">
                        <field name="history_count" widget="statinfo" string="Drivers History"/>
                    </button>
                    
                    
                    <button name="return_action_to_open" type="object" class="oe_stat_button" icon="fa-wrench" context="{'xml_id':'fleet_vehicle_log_services_action'}" help="show the services logs for this vehicle">
                        <field name="service_count" widget="statinfo" string="Services"/>
                    </button>
                    
                   
                    <button name="return_action_to_open" type="object" class="oe_stat_button" icon="fa-tachometer" context="{'xml_id':'fleet_vehicle_odometer_action'}" help="show the odometer logs for this vehicle">
                        <field name="odometer_count" widget="statinfo" string="Odometer"/>
                    </button>
               </div>
            </xpath>
            <xpath expr="//field[@name='next_assignation_date']" position="after">
                <field name="active"/>
            </xpath>
            <xpath expr="//form/sheet/group/group/field[@name='car_value']" position="after">
                <field name="income_acc_id" string="Income Account" required="1"/>
                <field name="expence_acc_id" string="Expense Account" required="1"/>
            </xpath>
            <xpath expr="//sheet/div[hasclass('oe_title')]" position="replace"/>
            <xpath expr="//field[@name='acquisition_date']" position="attributes">
                <attribute name="string">Registration Date</attribute>
                <attribute name="readonly">1</attribute>
            </xpath>
            <xpath expr="//field[@name='acquisition_date']" position="before">
                <field name="released_date"/>
                <field name="reg_id" readonly="1"/>
                <field name="vehicle_owner" required="1" options="{'no_open': True, 'no_create': True, 'no_create_edit': True}"/>
            </xpath>
            <xpath expr="//field[@name='acquisition_date']" position="after">
                <field name="updated_by" readonly="1"/>
                <field name="updated_date" readonly="1"/>
                <field name="warranty_period" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                <field name="increment_odometer" invisible="1"/>
            </xpath>
            <xpath expr="//field[@name='odometer']" position="attributes">
                <attribute name="attrs">{'readonly':[('state','in',('write-off'))]}</attribute>
            </xpath>
            <xpath expr="//field[@name='odometer_unit']" position="attributes">
                <attribute name="attrs">{'readonly':[('state','in',('write-off'))]}</attribute>
            </xpath>
            <xpath expr="//sheet/field[@name='image_128']" position="after">
                <div class="oe_title">
                <label for="f_brand_id" class="oe_edit_only"/>
                 <h1>
                     <field name="f_brand_id" required="1" class="oe_inline" options="{'no_open': True, 'create': false, 'create_edit': false}" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                 </h1>
               <group colspan="2" col="2">
                   <field name="model_id" class="oe_inline" domain="[('brand_id','=',f_brand_id)]" options="{'no_open': True, 'create': false, 'create_edit': false}" attrs="{'readonly':[('state','in',('write-off'))]}" context="{'default_brand_id': f_brand_id}"/>
                   <field name="model_no" class="oe_inline" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                   <field name="license_plate" class="oe_inline" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                   <field name="name" string="Vehicle-ID" readonly="1" attrs="{'readonly':[('state','in',('write-off'))]}"/>
               </group>
               </div>
            </xpath>
            <xpath expr="//field[@name='odometer']" position="after">
                <field name="odometer_check" invisible="1"/>
            </xpath>
            <xpath expr="//field[@name='odometer_unit']" position="attributes">
                <attribute name="attrs">{'readonly':[('odometer_check','=',False)]}</attribute>
            </xpath>
            <xpath expr="//field[@name='location']" position="replace"/>
            <xpath expr="//field[@name='driver_id']" position="before">
                <field name="vechical_type_id" options="{'no_open': True, 'create': false, 'create_edit': false}" attrs="{'readonly':[('state','in',('write-off'))]}"/>
            </xpath>
            <xpath expr="//field[@name='driver_id']" position="attributes">
                 <attribute name="attrs">{'readonly':[('state','in',('write-off'))]}</attribute>
                 <attribute name="domain">[('is_driver','=',True)]</attribute>
                 <attribute name="options">{'no_quick_create': True}</attribute>
                 <attribute name="context">{'default_is_driver':True}</attribute>
            </xpath>
            <xpath expr="//field[@name='driver_id']" position="after">
                <field name="driver_identification_no" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                <field name="driver_contact_no" string="Driver Contact Number" attrs="{'readonly':[('state','in',('write-off'))]}"/>
            </xpath>
            <xpath expr="//field[@name='vechical_type_id']" position="after">
                <field name="vehical_color_id" attrs="{'readonly':[('is_color_set','=',True)]}" options="{'no_open': True, 'create': false, 'create_edit': false}"/>
                <field name="vehicle_location_id" string="Registration State" attrs="{'readonly':[('state','in',('write-off'))]}" options="{'no_open': True, 'create': false, 'create_edit': false}"/>
                <field name="vehical_division_id" invisible="1" attrs="{'readonly':[('state','in',('write-off'))]}" options="{'no_open': True, 'create': false, 'create_edit': false}"/>
            </xpath>
            <xpath expr="//field[@name='car_value']" position="replace">
                <field name="car_value" invisible="1"/>
            </xpath>

            <xpath expr="//field[@name='company_id']" position="attributes">
                <attribute name="invisible">1</attribute>
            </xpath>

            
            <xpath expr="//form/sheet/group/group[5]" position="replace">
            </xpath>
            <xpath expr="//form/sheet/group/group[4]" position="replace">
            </xpath>
            <xpath expr="//form/sheet/group/group[3]" position="replace">
            </xpath>

            <xpath expr="//form/sheet/group[@col='2']" position="after">
                <notebook colspan="4">
                    <page string="Engine Specifications">
                        <group string="Engine Parameters">
                            <group colspan="2" col="4">
                                <field name="engine_no" attrs="{'readonly': [('is_engine_set','=',True)]}"/>
                                <field name="transmission" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="co2" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="engine_size" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="horsepower" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="cylinders" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="horsepower_tax" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="power" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                             </group>
                         </group>
                    </page>
                    <page string="Features">
                        <group string="">
                            <group string="Tire Detail">
                                <field name="tire_size" attrs="{'readonly':['|',('is_tire_size_set','=',True),('state','in',('write-off'))]}"/>
                                <field name="tire_srno" attrs="{'readonly':['|',('is_tire_srno_set','=',True),('state','in',('write-off'))]}"/>
                                <field name="tire_issuance_date" attrs="{'readonly':['|',('is_tire_issue_set','=',True),('state','in',('write-off'))]}"/>
                            </group>
                            <group string="Battery Detail">
                                <field name="battery_size" attrs="{'readonly':['|',('state','in',('write-off')),('is_battery_size_set','=',True)]}"/>
                                <field name="battery_srno" attrs="{'readonly':['|',('state','in',('write-off')),('is_battery_srno_set','=',True)]}"/>
                                <field name="battery_issuance_date" attrs="{'readonly':['|',('state','in',('write-off')),('is_battery_issue_set','=',True)]}"/>
                            </group>
                        </group>

                        <notebook colspan="4" string=" Information">
                            <page string="Dimensions And Capacity">
                                <group>
                                    <group col="2" string="Dimensions">
                                        <field name="vehicle_length" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                        <field name="vehicle_width" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                        <field name="vehicle_height" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                    </group>
                                    <group col="2" string="Capacity">
                                        <field name="seats" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                    </group>
                                </group>
                            </page>

                            <page string="Other Properties">
                                <group colspan="3" col="6">
                                    <field name="left_wiper_blade" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                    <field name="right_wiper_blade" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                    <field name="rr_wiper_blade" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                    <field name="doors" string="No of Doors" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                </group>
                            </page>

                        </notebook>
                    </page>
                    <page string="Fluids">
                        <group>
                            <group colspan="2" col="4" string="Fuel">
                                <field name="fuel_type" required="1" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="fuel_qty" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="fuel_capacity" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                            </group>
                            <group colspan="2" col="4" string="Oil">
                                <field name="oil_name" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="oil_capacity" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                            </group>
                        </group>
                    </page>

                    <page string="Service Details">
                        <group colspan="4" col="6">
                            <group string="Last Service">
                                <field name="last_service_date"/>
                                <field name="last_change_status_date"/>
                                <field name="last_service_by_id" readonly="1"/>
                            </group>
                            <group string="Next Service Due">
                                <field name="next_service_date"/>
                                <label for="due_odometer"/>
                                <div>
                                    <field name="due_odometer" class="oe_inline" readonly="1"/>
                                    <field name="due_odometer_unit" class="oe_inline" readonly="1"/>
                                </div>
                            </group>
                        </group>
                        <separator string="Work Orders" colspan="4" invisible="1"/>
                        <field name="work_order_ids" invisible="1">
                            <tree>
                                <field name="name"/>
                                <field name="service_type_id"/>
                                <field name="date" string="Issue Date"/>
                                <field name="date_open"/>
                                <field name="date_close"/>
                                <field name="state"/>
                            </tree>
                        </field>
                         <separator string="Pending Repair Types" colspan="4"/>
                         <field name="pending_repair_type_ids">
                            <tree>
                                <field name="vehicle_rep_type_id" invisible="1"/>
                                <field name="name"/>
                                <field name="repair_type_id"/>
                                <field name="categ_id"/>
                                <field name="issue_date"/>
                                <field name="state"/>
                                <field name="user_id"/>
                            </tree>
                            <form>
                                <group colspan="4" col="4">
                                    <field name="vehicle_rep_type_id" invisible="1" options="{'no_open': True, 'create': false, 'create_edit': false}"/>
                                    <field name="name"/>
                                    <field name="repair_type_id" readonly="1" options="{'no_open': True, 'create': false, 'create_edit': false}"/>
                                    <field name="categ_id" readonly="1"/>
                                    <field name="issue_date" readonly="1"/>
                                    <field name="state" readonly="1"/>
                                    <field name="user_id" readonly="1" options="{'no_open': True, 'create': false, 'create_edit': false}"/>
                                </group>
                            </form>
                         </field>
                    </page>
                    <page string="Sales &amp; Purchases" invisible="1">
                        <group col="2">
                            <field name="dealer_id" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                            <field name="car_value" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                            <field name="mileage" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                        </group>
                        <group string="Equipment Detail">
                            <group col="2">
                                <field name="buyer_id" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                            </group>
                            <group colspan="2" col="4">
                                <field name="date_sold" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="transfer_date" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                            </group>
                        </group>
                        <separator string="Attachments" colspan="4"/>
                        <field name="sale_purchase_attach_ids" nolabel="1" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                    </page>
                    <page string="Insurance Terms">
                        <group>
                            <group>
                                <field name="insurance_company_id" domain="[('insurance','=',True)]" options="{'no_quick_create': True}" attrs="{'readonly':[('state','in',('write-off'))]}" context="{'default_is_company':True,'default_insurance':True}"/>
                                <field name="insurance_type_id" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="start_date_insurance" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="end_date_insurance" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                            </group>
                            <group col="2">
                                <field name="policy_number" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="payment" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                                <field name="payment_deduction" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                            </group>
                        </group>
                    </page>
                    <page string="Attachments">
                        <field name="fleet_attach_ids" nolabel="1" attrs="{'readonly':[('state','in',('write-off'))]}"/>
                    </page>
                    <page string="Vehicle Images">
                        <field name="multi_images" widget="many2many_binary"/>
                            
                    </page>
                    <page string="History">
                        <group colspan="4" col="6">
                            <field name="is_color_set" invisible="1"/>
                            <field name="is_engine_set" invisible="1"/>
                            <field name="is_vin_set" invisible="1"/>
                            <field name="is_tire_size_set" invisible="1"/>
                            <field name="is_tire_srno_set" invisible="1"/>
                            <field name="is_tire_issue_set" invisible="1"/>
                            <field name="is_battery_size_set" invisible="1"/>
                            <field name="is_battery_srno_set" invisible="1"/>
                            <field name="is_battery_issue_set" invisible="1"/>
                        </group>
                        <separator string="Engine History" colspan="4"/>
                        <field name="engine_history_ids" nolabel="1">
                            <tree>
                                <field name="previous_engine_no" style="width:20%;"/>
                                <field name="new_engine_no"/>
                                <field name="changed_date" style="width:100%"/>
                                <field name="workorder_id"/>
                                <field name="note"/>
                            </tree>
                        </field>
                        <separator string="Vin History" colspan="4" invisible="1"/>
                        <field name="vin_history_ids" nolabel="1" invisible="1">
                            <tree>
                                <field name="previous_vin_no"/>
                                <field name="new_vin_no"/>
                                <field name="changed_date"/>
                                <field name="workorder_id"/>
                                <field name="note"/>
                            </tree>
                        </field>
                        <separator string="Color History" colspan="4"/>
                        <field name="color_history_ids" nolabel="1">
                            <tree>
                                <field name="previous_color_id"/>
                                <field name="current_color_id"/>
                                <field name="changed_date"/>
                                <field name="workorder_id"/>
                                <field name="note"/>
                            </tree>
                        </field>
                        <separator string="Tire History" colspan="4"/>
                        <field name="tire_history_ids" nolabel="1">
                            <tree>
                                <field name="previous_tire_size"/>
                                <field name="new_tire_size"/>
                                <field name="previous_tire_sn"/>
                                <field name="new_tire_sn"/>
                                <field name="previous_tire_issue_date"/>
                                <field name="new_tire_issue_date"/>
                                <field name="workorder_id"/>
                                <field name="changed_date"/>
                                <field name="note"/>
                            </tree>
                        </field>
                        <separator string="Battery History" colspan="4"/>
                        <field name="battery_history_ids" nolabel="1">
                            <tree>
                                <field name="previous_battery_size"/>
                                <field name="new_battery_size"/>
                                <field name="previous_battery_sn"/>
                                <field name="new_battery_sn"/>
                                <field name="previous_battery_issue_date"/>
                                <field name="new_battery_issue_date"/>
                                <field name="workorder_id"/>
                                <field name="changed_date"/>
                                <field name="note"/>
                            </tree>
                        </field>
                        </page>
                        <page string="Notes">
                             <separator string="Note" colspan="4"/>
                             <field nolabel="1" name="description" placeholder="Put an internal note..." attrs="{'readonly':[('state','in',('write-off'))]}"/>
                        </page>
                </notebook>
            </xpath>
            <xpath expr="//field[@name='engine_size']" position="attributes">
                <attribute name="string">Engine Model</attribute>
            </xpath>
        </data></field>
    </record>

**Comment by YogendrasinhChavda** [comment]
Hello @davidwoodroffe28-dev 

As per your error log, 
Field custom_product_id used in attrs.invisible ({'invisible': [('custom_product_id', '!=', False)]}) must be present in view but is missing.
"custom_product_id" this field is missing in view, but in our fleet modules don't have that field Or that kind of condition in any view. ( we already checked technically. )

So, make sure you have any other custom odoo application / modules is already installed on same instance / server ?

Thanks
