### ISSUE TITLE
Upgrade to v16

### ISSUE THREAD

**Issue by rpsjr** [JayVora-SerpentCS/fleet_management#77]
Are u guys willing to upgrade to v16?

**Comment by YogendrasinhChavda** [comment]
Hello @rpsjr ,

Yes, Our Team is working on it. We will push Fleet Management migrated addons soon for V16.

Thanks

**Comment by YogendrasinhChavda** [comment]
Hello @rpsjr 

V16 Migration is done by Our team.

Thanks
